variables:
  GIT_DEPTH: "1"

.run-checker:
  script:
    - checker-final2019 $CHECKER_CONFIG

test-master:
  extends: .run-checker
  image: $CHECKER_IMAGE:latest
  stage: test
  except:
    variables:
      - $CUSTOM_CHECKER

test-another-checker:
  extends: .run-checker
  image: $CHECKER_IMAGE:$CUSTOM_CHECKER
  stage: test
  only:
    variables:
      - $CUSTOM_CHECKER
